
# Default value.
field.value.digitalia_field_links:
  type: mapping
  label: Default value
  mapping:
    link_type:
      type: string
      label: Link type
    link_label:
      type: string
      label: Link label
    url:
      type: uri
      label: URL

# Field formatter.
field.formatter.settings.digitalia_field_links_default:
  type: mapping
  label: Example formatter settings
  mapping:
    foo:
      type: string
      label: Foo
